# Generated by Django 5.1.1 on 2024-10-06 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id_carrito', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cantidad_total_productos', models.IntegerField()),
                ('monto_carrito', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=10)),
                ('descripcion_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tfno', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_compra', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('monto_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora_pedido', models.TimeField(auto_now_add=True)),
                ('estado_pedido', models.BooleanField()),
                ('fecha_pedido', models.DateField()),
                ('cliente_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado_producto', models.BooleanField()),
                ('nombre_producto', models.CharField(max_length=30)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_producto', models.CharField(max_length=50)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('cantidad_producto', models.IntegerField()),
                ('cantidad_padmin', models.IntegerField()),
                ('cantidad_ppedido', models.IntegerField()),
                ('cantidad_pcarrito', models.IntegerField()),
                ('admin_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.administrador')),
                ('carrito_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.carritocompra')),
                ('categoria_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.categoria')),
                ('pedido_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario_aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario'),
        ),
    ]
